language: node_js

node_js:
  - v9.11.2

services:
  - postgresql

env:
  - DATABASE_URL="postgresql://codex:codex123@localhost/registrations";
  
before_script:
  - psql -c 'create database registrations;' -U postgres
  - psql -U postgres -d registrations -a -f tables.sql

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5

  